### PR TITLE
use the data-schema module

### PR DESCRIPTION
**Pull request by FenrirUnbound**
This work is related to relabeling the `data-schema` module, we need to update the plugins that utilize it for data validation.

### CODE REVIEW

**Comment by d2lam** [comment]
Test failed. I think you need to change triggeredBy in 
https://github.com/screwdriver-cd/plugin-jobs/blob/cf22b90b3e4be17f84aeb206a5f93275d73388dd/test/data/job.json
and 
https://github.com/screwdriver-cd/plugin-jobs/blob/cf22b90b3e4be17f84aeb206a5f93275d73388dd/test/data/jobs.json

**Comment by FenrirUnbound** [comment]
@d2lam Updated. I couldn't reproduce the issue with the old `data-model` module for some odd reason 😒

**Comment by nkatzman** [comment]
👍

**Comment by d2lam** [comment]
@FenrirUnbound  Which one did you try to reproduce with? 2.0.1 didn't have validation pattern for triggerBy yet so it passed. If you use the newest one (2.0.3) it would fail with the same error.

**Comment by d2lam** [comment]
👍

**Pull request merged**
